#!/bin/bash

# ================================================
# PixelNotes Manual Upload Guide
# Target: creativepixels.in/Notes/
# ================================================

echo "📋 PixelNotes Upload Instructions"
echo "=================================="
echo ""
echo "Since automated FTP isn't working, here are 3 easy methods:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 1: FileZilla (Recommended) 🎯"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Download FileZilla: https://filezilla-project.org/"
echo "2. Open FileZilla"
echo "3. Enter connection details:"
echo "   Host: ftp.creativepixels.in"
echo "   Username: u258849571"
echo "   Password: Deloitte@001"
echo "   Port: 21"
echo ""
echo "4. Click 'Quickconnect'"
echo "5. Navigate to: /domains/creativepixels.in/public_html/"
echo "6. Right-click → Create directory → Name it: Notes"
echo "7. Double-click to open 'Notes' folder"
echo "8. From left panel, navigate to:"
echo "   $(pwd)/PixelNotes/"
echo ""
echo "9. Select these 4 files and drag to right panel:"
echo "   ☑ login.html"
echo "   ☑ dashboard.html"
echo "   ☑ editor.html"
echo "   ☑ landing.html"
echo ""
echo "10. Wait for upload to complete ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 2: GoDaddy File Manager (Web-based) 🌐"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Login to GoDaddy: https://www.godaddy.com/"
echo "2. Go to: My Products → Web Hosting → Manage"
echo "3. Click: 'File Manager' or 'cPanel'"
echo "4. Navigate to: public_html/"
echo "5. Click: 'New Folder' → Name it: Notes"
echo "6. Open 'Notes' folder"
echo "7. Click: 'Upload Files'"
echo "8. Select from: $(pwd)/PixelNotes/"
echo "   - login.html"
echo "   - dashboard.html"
echo "   - editor.html"
echo "   - landing.html"
echo "9. Click 'Upload' ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 3: Using macOS Finder (Easiest!) 📁"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open Finder"
echo "2. Press: Cmd + K (or Go → Connect to Server)"
echo "3. Enter: ftp://u258849571:Deloitte@001@ftp.creativepixels.in"
echo "4. Click 'Connect'"
echo "5. Navigate to: domains/creativepixels.in/public_html/"
echo "6. Create folder: Notes"
echo "7. Copy files from PixelNotes/ to Notes/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After Upload:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Test Demo Mode:"
echo "   https://creativepixels.in/Notes/login.html"
echo "   Click: 'Try Demo Mode (No Login Required)'"
echo ""
echo "✅ Setup Google OAuth (Optional):"
echo "   1. Go to: https://console.cloud.google.com/apis/credentials"
echo "   2. Edit Client: 264150556588-j05rnbhdtpsv0ha0la7g1v4479v5cm9l"
echo "   3. Add JavaScript origins:"
echo "      • https://creativepixels.in"
echo "   4. Add Redirect URIs:"
echo "      • https://creativepixels.in/Notes/login.html"
echo "      • https://creativepixels.in/Notes/dashboard.html"
echo "   5. Save changes"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📂 Files Location (Copy from here):"
echo "   $(pwd)/PixelNotes/"
echo ""
ls -lh "$(pwd)/PixelNotes/"*.html 2>/dev/null || echo "   ⚠️  Check PixelNotes folder exists"
echo ""
echo "🎯 Target Server Path:"
echo "   /domains/creativepixels.in/public_html/Notes/"
echo ""
echo "💡 Tip: I recommend FileZilla - it's free, easy, and reliable!"
echo ""
