"""
Pixel Fact Integrator - Integrates generated articles with Pixel Fact platform
"""

import os
import json
import shutil
from datetime import datetime
from typing import Dict, List

class PixelFactIntegrator:
    """Integrate generated articles with Pixel Fact"""
    
    def __init__(self, config_path: str = "../config.json"):
        """Initialize integrator"""
        self.config = self._load_config(config_path)
        self.pixelfact_data_path = "../frontend/PixelFact/js/articles-data.js"
        self.generated_articles = []
        
    def _load_config(self, path: str) -> Dict:
        """Load configuration"""
        with open(path, 'r') as f:
            return json.load(f)
    
    def add_article(self, article: Dict) -> bool:
        """
        Add article to Pixel Fact platform
        
        Args:
            article: Article dictionary
            
        Returns:
            True if successful
        """
        print(f"🔗 Integrating article: {article['title']}")
        
        try:
            # Load existing articles
            existing_articles = self._load_existing_articles()
            
            # Add new article
            existing_articles.append(article)
            
            # Update articles data file
            self._update_articles_data(existing_articles)
            
            # Save to generated folder
            self._save_to_generated_folder(article)
            
            print(f"✅ Article integrated successfully")
            return True
            
        except Exception as e:
            print(f"❌ Integration failed: {e}")
            return False
    
    def _load_existing_articles(self) -> List[Dict]:
        """Load existing articles from Pixel Fact"""
        try:
            # Check if data file exists
            if os.path.exists(self.pixelfact_data_path):
                with open(self.pixelfact_data_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                    
                # Extract JSON array from JavaScript file
                start = content.find('[')
                end = content.rfind(']') + 1
                
                if start != -1 and end != 0:
                    json_str = content[start:end]
                    return json.loads(json_str)
            
            # Return default articles if file doesn't exist
            return self._get_default_articles()
            
        except Exception as e:
            print(f"⚠️  Error loading existing articles: {e}")
            return self._get_default_articles()
    
    def _get_default_articles(self) -> List[Dict]:
        """Get default articles structure"""
        return []
    
    def _update_articles_data(self, articles: List[Dict]):
        """Update articles data JavaScript file"""
        
        # Create JavaScript content
        js_content = f"""// Pixel Fact Articles Data
// Auto-generated by Pixel Write
// Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

const articlesData = {json.dumps(articles, indent=2, ensure_ascii=False)};

// Export for use in app
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = articlesData;
}}
"""
        
        # Ensure directory exists
        os.makedirs(os.path.dirname(self.pixelfact_data_path), exist_ok=True)
        
        # Write to file
        with open(self.pixelfact_data_path, 'w', encoding='utf-8') as f:
            f.write(js_content)
        
        print(f"💾 Updated: {self.pixelfact_data_path}")
    
    def _save_to_generated_folder(self, article: Dict):
        """Save article to generated folder"""
        output_dir = self.config['output']['output_directory']
        os.makedirs(output_dir, exist_ok=True)
        
        filename = f"article_{article['id']}_{datetime.now().strftime('%Y%m%d')}.json"
        filepath = os.path.join(output_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(article, f, indent=2, ensure_ascii=False)
    
    def get_article_count(self) -> int:
        """Get total number of articles"""
        articles = self._load_existing_articles()
        return len(articles)
    
    def list_recent_articles(self, limit: int = 5) -> List[Dict]:
        """List most recent articles"""
        articles = self._load_existing_articles()
        
        # Sort by date
        sorted_articles = sorted(
            articles,
            key=lambda x: x.get('date', ''),
            reverse=True
        )
        
        return sorted_articles[:limit]
    
    def cleanup_old_articles(self, keep_days: int = 30):
        """Remove articles older than specified days"""
        from datetime import timedelta
        
        articles = self._load_existing_articles()
        cutoff_date = (datetime.now() - timedelta(days=keep_days)).strftime('%Y-%m-%d')
        
        # Filter articles
        filtered_articles = [
            article for article in articles
            if article.get('date', '9999-12-31') >= cutoff_date
        ]
        
        removed_count = len(articles) - len(filtered_articles)
        
        if removed_count > 0:
            self._update_articles_data(filtered_articles)
            print(f"🗑️  Removed {removed_count} old articles")
        
        return removed_count


# Example usage
if __name__ == "__main__":
    integrator = PixelFactIntegrator()
    
    # Test article
    test_article = {
        "id": 999,
        "title": "Test Article from Pixel Write",
        "category": "Technology",
        "author": "Pixel AI Writer",
        "date": datetime.now().strftime("%Y-%m-%d"),
        "readTime": "5 min",
        "excerpt": "This is a test article generated by Pixel Write automation system.",
        "content": "Full test content here...",
        "tags": ["Test", "Automation", "AI"],
        "image": "/images/blog-999.jpg",
        "featured": False,
        "trending": True,
        "views": 0
    }
    
    # Add test article
    integrator.add_article(test_article)
    
    # List recent
    recent = integrator.list_recent_articles(3)
    print(f"\n📚 Recent Articles ({len(recent)}):")
    for article in recent:
        print(f"  - {article['title']} ({article['date']})")
